/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/auth/Error': RouteRecordInfo<'/auth/Error', '/auth/Error', Record<never, never>, Record<never, never>>,
    '/auth/Login': RouteRecordInfo<'/auth/Login', '/auth/Login', Record<never, never>, Record<never, never>>,
    '/auth/Register': RouteRecordInfo<'/auth/Register', '/auth/Register', Record<never, never>, Record<never, never>>,
    '/auth/reset-password/': RouteRecordInfo<'/auth/reset-password/', '/auth/reset-password', Record<never, never>, Record<never, never>>,
    '/auth/reset-password/[token]': RouteRecordInfo<'/auth/reset-password/[token]', '/auth/reset-password/:token', { token: ParamValue<true> }, { token: ParamValue<false> }>,
    '/auth/Unauthorized': RouteRecordInfo<'/auth/Unauthorized', '/auth/Unauthorized', Record<never, never>, Record<never, never>>,
    '/Crud': RouteRecordInfo<'/Crud', '/Crud', Record<never, never>, Record<never, never>>,
    '/Dashboard': RouteRecordInfo<'/Dashboard', '/Dashboard', Record<never, never>, Record<never, never>>,
    '/Documentation': RouteRecordInfo<'/Documentation', '/Documentation', Record<never, never>, Record<never, never>>,
    '/profile': RouteRecordInfo<'/profile', '/profile', Record<never, never>, Record<never, never>>,
    '/README': RouteRecordInfo<'/README', '/README', Record<never, never>, Record<never, never>>,
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>>,
    '/uikit/ButtonDoc': RouteRecordInfo<'/uikit/ButtonDoc', '/uikit/ButtonDoc', Record<never, never>, Record<never, never>>,
    '/uikit/ChartDoc': RouteRecordInfo<'/uikit/ChartDoc', '/uikit/ChartDoc', Record<never, never>, Record<never, never>>,
    '/uikit/FileDoc': RouteRecordInfo<'/uikit/FileDoc', '/uikit/FileDoc', Record<never, never>, Record<never, never>>,
    '/uikit/FormLayout': RouteRecordInfo<'/uikit/FormLayout', '/uikit/FormLayout', Record<never, never>, Record<never, never>>,
    '/uikit/InputDoc': RouteRecordInfo<'/uikit/InputDoc', '/uikit/InputDoc', Record<never, never>, Record<never, never>>,
    '/uikit/ListDoc': RouteRecordInfo<'/uikit/ListDoc', '/uikit/ListDoc', Record<never, never>, Record<never, never>>,
    '/uikit/MediaDoc': RouteRecordInfo<'/uikit/MediaDoc', '/uikit/MediaDoc', Record<never, never>, Record<never, never>>,
    '/uikit/MenuDoc': RouteRecordInfo<'/uikit/MenuDoc', '/uikit/MenuDoc', Record<never, never>, Record<never, never>>,
    '/uikit/MessagesDoc': RouteRecordInfo<'/uikit/MessagesDoc', '/uikit/MessagesDoc', Record<never, never>, Record<never, never>>,
    '/uikit/MiscDoc': RouteRecordInfo<'/uikit/MiscDoc', '/uikit/MiscDoc', Record<never, never>, Record<never, never>>,
    '/uikit/OverlayDoc': RouteRecordInfo<'/uikit/OverlayDoc', '/uikit/OverlayDoc', Record<never, never>, Record<never, never>>,
    '/uikit/PanelsDoc': RouteRecordInfo<'/uikit/PanelsDoc', '/uikit/PanelsDoc', Record<never, never>, Record<never, never>>,
    '/uikit/TableDoc': RouteRecordInfo<'/uikit/TableDoc', '/uikit/TableDoc', Record<never, never>, Record<never, never>>,
    '/uikit/TimelineDoc': RouteRecordInfo<'/uikit/TimelineDoc', '/uikit/TimelineDoc', Record<never, never>, Record<never, never>>,
    '/uikit/TreeDoc': RouteRecordInfo<'/uikit/TreeDoc', '/uikit/TreeDoc', Record<never, never>, Record<never, never>>,
  }
}
